### ISSUE TITLE
.info .module and .install files and config folder need to be moved one level up in the folder structure.

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/analyzers#1]
current:
```
custom_theme_analyzer/config/custom_theme_analyzer.settings.json
custom_theme_analyzer/custom_theme_analyzer.info
custom_theme_analyzer/custom_theme_analyzer.install
custom_theme_analyzer/custom_theme_analyzer.module
LICENSE.txt
README.md
```
how it should be:
```
config/custom_theme_analyzer.settings.json
custom_theme_analyzer.info
custom_theme_analyzer.install
custom_theme_analyzer.module
LICENSE.txt
README.md
```

---
PR by @klonos: https://github.com/backdrop-contrib/analyzers/pull/2

**Comment by ghost** [comment]
This project is a collection of small modules. Currently it only includes Custom Theme Analyzer but with the time new modules will be added. Each modules should be located in its directory and not in the main directory.

**Comment by klonos** [comment]
Fair enough. Just noticed that. Closing issue and PR. Sorry for the noise.
